### ISSUE TITLE
Link directly to specific page

### ISSUE THREAD

**Issue by jeffreyvr** [ts1/flipbook-vue#10]
Hi,

This looks very promising!

I took a quick look at the code, but could not figure out if it is possible to link to a page directly (through a direct URL). Or is that something that one would/should implement?

**Comment by ts1** [comment]
Hi @jeffreyvr 
That feature is not implemented yet.
I'm considering to add a property to specify initial page number.

**Comment by bpieres** [comment]
Any news about this feature? Thanks!

**Comment by ts1** [comment]
@bpieres  This has been implemented as `startPage` prop.

**Comment by ts1** [comment]
@bpieres  This has been implemented as `startPage` prop.

**Comment by ts1** [comment]
@bpieres  This has been implemented as `startPage` prop.

**Comment by bpieres** [comment]
Great and there is any way to add links inside a page?

**Comment by ts1** [comment]
For linking, see my demo page and it's [source code](https://github.com/ts1/flipbook-vue/tree/master/examples/demo).
You can link directly like this: https://ts1.github.io/flipbook-vue/#4
