### ISSUE TITLE
Event to Zoom-in

### ISSUE THREAD

**Issue by spacedog4** [ts1/flipbook-vue#11]
I'd like to have an event to know when the user zoom-in ou zoom-out, so this way a could make it become full screen

**Comment by spacedog4** [comment]
What I have to do for now 

```
document.querySelector('.flipbook .bounding-box').addEventListener('click', e => {
    clearInterval(interval)
    interval = setInterval(() => {
        if (!this.$refs.flipbook.zooming) {
            this.zoom = this.$refs.flipbook.zoom
            clearInterval(interval)
        }
    }, 100)
})
```

and based on that zoom if is bigger than 1 I change my page

**Comment by ts1** [comment]
Hi @spacedog4 
That feature would be nice to have.
I'll implement it some time soon.
