### ISSUE TITLE
Zoom on Safari

### ISSUE THREAD

**Issue by mcweekly** [ts1/flipbook-vue#14]
I've tried the demo on a few versions of Safari where zoom isn't working properly like it does on Chrome (Mac) or Windows. When I click for zoom it expands beyond the page towards the top left corner no matter where the mouse is pointed.

Safari 13.0.5 / MacOS 10.14.6

I will add more examples when I get them, I'm waiting to here back from my employer on what version he is on (both iPad and laptop).

It's really a great component, very smooth and pretty animations.

**Comment by mcweekly** [comment]
Safari 13.0.5 / OS 1.15.3 (Catalina)
iPad Safari 13.3.1

**Comment by ts1** [comment]
@mcweekly Thanks for the report.
I confirmed the problem.
I'll investigate it sometime soon.

**Comment by ts1** [comment]
I reverted https://github.com/ts1/flipbook-vue/commit/fe7cd467b1cfefa463b3b748b83ccb862737ef77.
Apparently this broke scrolling behavior on Safari.
