### ISSUE TITLE
Lazy effect

### ISSUE THREAD

**Issue by dev-ccazares** [ts1/flipbook-vue#15]
Hello, thank you for this package that you contribute to us, but I would like to know if you can put a lazy effect when loading the pages, since on my website the images take about 2 seconds to get from the server and it doesn't look good, it would be good to implement a load no I know if you can help me with that or can you tell me how I could put it

**Comment by ts1** [comment]
Hello @dev-ccazares 
Thanks for the input.
That's a feature I'd like to realize, so I'll be looking into how to implement it for a while.

**Comment by maxiz22** [comment]
+1 with lazy loading , it would load very quickly

**Comment by ts1** [comment]
On v0.9.0 image loading effect and `loadingImage` prop is added. Default is a built-in spinning circle SVG.
