### ISSUE TITLE
Errors building for production in Gridsome project

### ISSUE THREAD

**Issue by eoinom** [ts1/flipbook-vue#16]
Hi there,

I really like the look of this component and want to use it in my Gridsome project but unfortunately I'm getting errors when I try to build it for production. At first I installed it as a module using yarn and imported into my component as follows:

    <script>
    import Flipbook from 'flipbook-vue'
    export default {
      components: { 
	      Flipbook 
      }
    }
    </script>

This gave me the following error:

    ReferenceError: navigator is not defined
        at Object.423 (node_modules/flipbook-vue/dist/flipbook.es.js:78:0)
        at __webpack_require__ (webpack/bootstrap:25:0)
        at Module.428 (assets/js/page--src-templates-publication-vue.9c43d4d3.js:111:19)
        at __webpack_require__ (webpack/bootstrap:25:0)

I then tried changing the import to the following (a suggestion from a Gridsome support group): 

    <script>
    export default {
      components: { 
	      Flipbook: () => import("flipbook-vue") 
	  }
    }
    </script>

But that gave me this error:

    Error: render function or template not defined in component: Flipbook
        at Qi ([Path to project]\node_modules\vue-server-renderer\build.prod.js:1:66749)
        at io ([Path to project]\node_modules\vue-server-renderer\build.prod.js:1:70622)
        at ro ([Path to project]\node_modules\vue-server-renderer\build.prod.js:1:70272)
        at i ([Path to project]\node_modules\vue-server-renderer\build.prod.js:1:68876)

I've also tried importing globally and bringing in the coffeescript files (I'm not familiar with them so I probably didn't do that right) but to no avail.

Would really appreciate your help on this. FYI, I created a CodeSandbox here (https://codesandbox.io/s/red-lake-j70rk?file=/src/components/BookViewer.vue) for testing also.

Thanks in advance!

**Comment by dad2cl3** [comment]
@eoinom I ran into a similar issue while trying to use the component in nuxt.js. The component is not built to support server-side only. I had to wrap it within nuxt.js to only render on the client side. I'm guessing you'll need to do the same in gridsome but have not built anything with gridsome myself. A quick search found this closed issue in the gridsome repo https://github.com/gridsome/gridsome/issues/180. Maybe it will help in your situation.

Jason

**Comment by eoinom** [comment]
> @eoinom I ran into a similar issue while trying to use the component in nuxt.js. The component is not built to support server-side only. I had to wrap it within nuxt.js to only render on the client side. I'm guessing you'll need to do the same in gridsome but have not built anything with gridsome myself. A quick search found this closed issue in the gridsome repo [gridsome/gridsome#180](https://github.com/gridsome/gridsome/issues/180). Maybe it will help in your situation.
> 
> Jason

Cheers Jason. Yeah I think I might have seen that issue in nuxt, or one like it, but didn't know how to do similar for Gridsome. I'll take a look at that link however, thanks a million.

**Comment by eoinom** [comment]
Thanks Jason, that issue led me to this part of the docs, [https://gridsome.org/docs/assets-scripts/#without-ssr-support](https://gridsome.org/docs/assets-scripts/#without-ssr-support), which details to wrap the component in `<ClientOnly></ClientOnly>` tags. Thanks for your help! 😀

**Comment by ts1** [comment]
Thanks @dad2cl3
