### ISSUE TITLE
Jump to page featue

### ISSUE THREAD

**Issue by AndrewKaisser** [ts1/flipbook-vue#17]
is there a possible way to have a jump to page feature?

**Comment by ts1** [comment]
Change `startPage` property.

**Comment by RainKolwa** [comment]
Is it possible to jump to page with flip animations?

**Comment by ts1** [comment]
Not at the moment.

**Comment by gouflv** [comment]
> Is it possible to jump to page with flip animations?

+1, Hope for this feature

**Comment by iHadDream** [comment]
+1111111
