### ISSUE TITLE
nuxtjs support

### ISSUE THREAD

**Issue by dad2cl3** [ts1/flipbook-vue#2]
Phenomenal repo that fits perfectly with a project i'm working on so thank you! Any chance you might be willing to add support for nuxtjs?

Thanks,

Jason

**Comment by ts1** [comment]
I'm not familiar with nuxt.js but, I think this can not be SSR'd because it deeply depends on runtime only features like viewport size, image size, etc.
Could it work if you configure this component used client side only?

**Comment by dad2cl3** [comment]
Great suggestion. I’ll definitely give it a shot!

**Comment by dad2cl3** [comment]
Wanted to check back in to say I finally had an opportunity to work on getting the component working on the client side only and so far so good.

First create a plugin for nuxt named flipbook.js with the following code:
`import Vue from 'vue'`
`import Flipbook from 'flipbook-vue'`
`Vue.component('Flipbook', Flipbook)
`

Then register the component within the plugins section of nuxt.config.js with the following code:
`
{ src: '@/plugins/flipbook', mode: 'client' }
`

From there, add the component to a Vue file using `<Flipbook class="book"...></Flipbook>`

Again, amazing library and exactly what I was looking for to complete my project.

Thanks again,

Jason

**Comment by piotrbekas** [comment]
> From there, add the component to a Vue file using `<Flipbook class="book"...></Flipbook>`

I found, that when using `nuxt generate` the `<client-only>` tag helps.

So you could use it like this:
```
<client-only>
  <Flipbook class="book"...></Flipbook>
</client-only>
```

**Comment by kissu** [comment]
I found a working solution [for Nuxt3](https://github.com/ts1/flipbook-vue/issues/87#issuecomment-2101350795).
