### ISSUE TITLE
I can't center the flipbook

### ISSUE THREAD

**Issue by edmi1994** [ts1/flipbook-vue#23]
good afternoon with everyone maybe someone has had problems with the centering of the flipbook? I can not center it or with centering
![image](https://user-images.githubusercontent.com/48374193/92334302-30818300-f052-11ea-8746-80a8af33556b.png)
![image](https://user-images.githubusercontent.com/48374193/92334304-37a89100-f052-11ea-80e7-e2d1b395c901.png)

**Comment by ts1** [comment]
Hello, It seems more like a problem with the html/css that surrounds it rather than a problem with the Flipbook.

**Comment by ts1** [comment]
Feel free to reopen if you still have problem.
