### ISSUE TITLE
Feature.  Don't reload images every time

### ISSUE THREAD

**Issue by pauubach** [ts1/flipbook-vue#27]
Hi,
As I change page the image is reloaded, it doesn't matter if we have already visited this page. Pages already loaded shouldn't be loaded again. 

Could it be fixed??

BTW, wonderful flipbook :).

**Comment by ts1** [comment]
I guess it's because of web server's configuration, images are not cached by browser.
Flipbook doesn't do anything special about loading image. (If the browser has cache, it uses cache)

**Comment by ts1** [comment]
I believe this issue is resolved.
Feel free to reopen if it is not.
