### ISSUE TITLE
Pass the response from an api

### ISSUE THREAD

**Issue by shubhra14** [ts1/flipbook-vue#3]
Thank for this beautiful component.

I have an issue with passing the array from an api to the pages prop.

This is how i'm getting my api response that has a property "media_full" that I need to extract and convert into an array for flipbook

```
  computed: {
    posts() {
      return this.$store.getters.requestedItems(this.request) <--- my response array
    }
  },
```

I tried this but it doesn't work but I see the correct image urls array in my console
```
posts() {
      let array = this.$store.getters.requestedItems(this.request)
      var finalArray = array.map(function (obj) {
            return obj.media_full;
        });
        console.log(finalArray);
    }
```

**Comment by shubhra14** [comment]
I am able to make this work using .map, however, flipbook isn't working as expected.
```
  computed: {
    posts() {
      return this.$store.getters.requestedItems(this.request)
    },
    imagesArray () {
      return this.posts.map(item => {
        return item.media_full
      })
    }
  },
```
imagesArray is returning 3 images currectly, however, flipbook is only showing me 2 images and the page number count is also incorrect. Please see the screenshot below
![Untitled-1](https://user-images.githubusercontent.com/5490862/60477028-6a5f3880-9c9b-11e9-994b-7b24036b95e1.jpg)

**Comment by ts1** [comment]
Sorry for the late reply @shubhra14, I've missed it. (GitHub didn't notified me)
I'll definitely look into it!

**Comment by shubhra14** [comment]
Thank you. I appreciate it.

**Comment by ts1** [comment]
Thanks for the details @shubhra14, I think I fixed this asynchronous pages initialization case.
Could you try v0.5.1 to see if it's fixed?

**Comment by shubhra14** [comment]
I will test this and get back to you. I appreciate you looking into this.

**Comment by shubhra14** [comment]
I have tested this and it's showing strange behaviour. It doesn't work when the page initially loads but starts working when I view it the 2nd time..
![flipbook2](https://user-images.githubusercontent.com/5490862/61075418-931fc480-a437-11e9-9d98-fd6ead1abd22.gif)

**Comment by ts1** [comment]
Hmm that's strange.
I'll try to reproduce the issue.
Thanks for the report.

**Comment by shubhra14** [comment]
I'm using this wordpress theme - https://github.com/bucky355/vue-wordpress

It would probably be better to test with it.

Thank you for your time.

**Comment by ts1** [comment]
I just published v0.5.2. Could you try this again @shubhra14 ?
I could not reproduce the bug, but obviously the cache of number of pages is not updated reactively for some reason.
I forgot why I cached it but now the code became straight forward a little bit.

**Comment by shubhra14** [comment]
Hi @ts1 , it's working perfectly now. Thank you so much for giving your valuable time on this. Cheers!

**Comment by ts1** [comment]
Good news! Thanks!
