### ISSUE TITLE
onFlipLeft and onFlipRight events

### ISSUE THREAD

**Issue by zacktayl** [ts1/flipbook-vue#4]
Hey!

Really liking this library. What do you think about adding events for 'on-flip-right' and 'on-flip-left'?

I would like to know when users go to the next page (for swipe, clicking gutters, or some other means).

Let me know what you think! I would be willing to make a PR with a suggested implementation if you like?

Thanks

**Comment by ts1** [comment]
Thanks for the suggestion @zacktayl!
I've been also thinking about those events.
IMO we should have two events per direction, before-flip and after-flip, before and after animation respectively.
PR is welcome!

**Comment by thefun126** [comment]
wait your nice work

**Comment by zacktayl** [comment]
Ok cool! It may be a bit before I can dive in and add the events. For now, I've setup a ref on the component and then used a watcher on currentPage:

```
onMounted(() => {
      watch(() => refs.flipbook.currentPage, (newVal, oldVal) => {
        if (newVal > oldVal) onFlipRight(refs.flipbook)
        if (newVal < oldVal) onFlipLeft(refs.flipbook)
      })
    })
```

fyi - The above is using the function-api rfc plugin

**Comment by zacktayl** [comment]
Thanks for adding this, @ts1!
