### ISSUE TITLE
Multiple books

### ISSUE THREAD

**Issue by Alex-Aeg** [ts1/flipbook-vue#43]
Great library!

Trying to use multiple books in either in the same .html or in multiple. Currently the pages array is inside the app.js file.
How can I move the pages images to an outside js file or (even better) in the html file to render multiple books?

Keep up the great work!

**Comment by ts1** [comment]
If I understand you correctly, you can just change `flipbookPages` for each html page in the following example.

```html
<html>
  <head>
    <style>
      .flipbook {
        margin: 0 auto;
        width: 90vw;
        height: 90vh;
      }
    </style>
  </head>
  <body>
    <div id="app">
      <template>
        <flipbook class="flipbook" :pages=pages></flipbook>
      </template>
    </div>
    <script>
      var flipbookPages = [
        'image1.jpg',
        'image2.jpg',
        'image3.jpg'
      ]
    </script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    <script src="https://unpkg.com/flipbook-vue"></script>
    <script>
      new Vue({
        el: "#app",
        data: { pages: flipbookPages }
      })
    </script>
  </body>
</html>
```

**Comment by Alex-Aeg** [comment]
Thanks. How to pass props like zooms and singlePage in that format?
Tried in the data object but didn't work.

**Comment by ts1** [comment]
Just change this line.
```html
        <flipbook class="flipbook" :pages=pages :zooms=null :single-page=true></flipbook>
```
If you want to change these like `pages`, use `data`.

**Comment by Alex-Aeg** [comment]
Perfect. Was trying :singlePage=singlePage with value in data, but didn't work.
Like this works :)
