### ISSUE TITLE
Option to show a single image per page

### ISSUE THREAD

**Issue by shubhra14** [ts1/flipbook-vue#6]
Hi,

Is it possible to show a single large image per page instead of two?

My images have text on them and are horizontal (1024px x 576px). So it becomes a bit difficult to read the text when they are shown in 500px coz width is getting divided for two images.

Thank you

**Comment by ts1** [comment]
Hi @shubhra14 
OK, I'll add that option and release soon.

**Comment by shubhra14** [comment]
You are amazing and this is working great, however, only one small issue. It's starting from page 2 and not 1.

Thank you for your time :)

**Comment by ts1** [comment]
@shubhra14 I fixed that bug. Please try v0.6.1.

**Comment by shubhra14** [comment]
It's fixed. Thank you!
