### ISSUE TITLE
Unable to run on HTML

### ISSUE THREAD

**Issue by murvinlai** [ts1/flipbook-vue#61]
i tried to put that in html but it doesn't work....

    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.1.0/dist/quasar.umd.prod.js"></script>
    <script src="https://unpkg.com/flipbook-vue"></script>

and the error I got from browser is:

flipbook-vue:29 Uncaught TypeError: Vue.component is not a function
    at flipbook-vue:29
    at flipbook-vue:29

**Comment by ts1** [comment]
Vue 3.x is not supported yet.
Use Vue 2.x instead.
