### ISSUE TITLE
2 Get request sent even though singlePage prop is used 

### ISSUE THREAD

**Issue by seonwoo960000** [ts1/flipbook-vue#64]
it sends 2 Get requests to the server when I flip to the next page 
![image](https://user-images.githubusercontent.com/69591622/149541598-f015ce2e-44b4-40d2-8580-f12ff102972e.png)

my code is 
`<flip-book class="flipbook" :pages="pages" v-slot="flipbook" ref="flipbook" singlePage>`

**Comment by seonwoo960000** [comment]
this behavior sends duplicate requests for the same image whenever I flip to next page. Btw I love "flipbook-vue", it's so wonderful

**Comment by ts1** [comment]
I guess the second one is the prefetch.
This component prefetches the images for the smooth user experience.
You may see the same image is fetched multiple times (prefetch and real `img`), but it should be served from browser's cache, so that should not be a problem.

**Comment by seonwoo960000-kim** [comment]
thank you for the reply ~
