### ISSUE TITLE
Remove zoom pointer when only one zoom level

### ISSUE THREAD

**Issue by pintaf** [ts1/flipbook-vue#7]
Hello.

Thanks for this nice work.
I have an improvement idea not so hard to do:

When the prop "zooms" contains an array of only one value then the zoom ou/in pointers should disapear.

Also other issue maybe more complicated to solve:
When passing null to the prop "zooms", the flipbook doesn't display anything. It would be nice it could behave like it receive [1] when receiving null.

**Comment by ts1** [comment]
Thank you for the suggestion @pintaf.
I'll definitely work on it.

**Comment by pintaf** [comment]
Tested it right now, works like a charm! thanks !
