### ISSUE TITLE
canFlipLeft / canFlipRight is false when current page is less than numPages

### ISSUE THREAD

**Issue by jordanmarshall12** [ts1/flipbook-vue#76]
Hello,

I have an issue where the component is setting canFlipLeft/Right and canGoForward/Back to false when I am on a page number that is significantly less than than the total (numPages). My flipbook has a cover page + 4 interior spreads. The library works fine for flipping my first few times, but I don't get the page flipping effect when I attempt to go to spread 3 because of the false values mentioned above. Thanks for any input you might have!

I've attached some screenshots for reference -

![pages_screenshot](https://user-images.githubusercontent.com/18316292/180235324-ac508d7f-93e1-47e2-9126-a8313fe2c87a.png)

![canGo_screenshot](https://user-images.githubusercontent.com/18316292/180235357-6047bf43-45d1-4e84-b371-9435792f24e8.png)

**Comment by ts1** [comment]
Can you provide a minimum set of a fully working application that reproduce the bug?

**Comment by jordanmarshall12** [comment]
I think I have the issue resolved. Closed issue #68 was helpful - I renamed all of the images to have a unique name and it looks like it's working. Thanks for your time!
