### ISSUE TITLE
Background transparent on flipped page animation

### ISSUE THREAD

**Issue by aqordeon** [ts1/flipbook-vue#90]
Hi, anyway thanks for the package.

I facing an issue which is the flipped page is transparent on animation and appear instantly when the animation is finished. Did anybody ever face this issue? Or was just I wrong when implemented it? I use Nuxt 3.

**Comment by aqordeon** [comment]
SOLVED.
This issue is strange.
The issue occurs because the filename of the image contains a space, "123 abc.jpg" would occur the issue, but "123abc.jpg" would work well.

**Comment by gusberinger** [comment]
I found a workaround to this issue. Replacing invalid characters with their encoded equivalents before passing the list of urls to the component fixes the bug.

```javascript
data() {
    const urls = originalUrlList.map((url) => {
      return url.replace("(", "%28").replace(")", "%29").replace(" ", "%20")
    })
    return {
      pages: [null, ...urls],
      hasMouse: true,
      pageNum: null,
    }
}

```
