### ISSUE TITLE
Switching pages fast with arrow keys messes up the images

### ISSUE THREAD

**Issue by Pajicc** [ts1/flipbook-vue#91]
If I switch pages too fast using arrow keys, it messes up the images, they get mixed up.
Is there a way we can disable arrow key events, or disable them while the images are loading or while the page is transitioning?

**Comment by ts1** [comment]
I think flipbook-vue itself does not handle keyboard events.
If you copied key event handler from `demo`, just remove it.

**Comment by Pajicc** [comment]
You're right. But I've found out I had some other component that interfered with keyboard events which I copied from the demo example. Events in the demo actually work ok. I'll close this issue, thanks.
