### ISSUE TITLE
Force odd/even pages to show on certain side of the flipbook

### ISSUE THREAD

**Issue by Pajicc** [ts1/flipbook-vue#99]
Is it possible to show odd number pages always on the right?
In my case, I have a slider that I mapped to the flipbook and I'm using it to change the pages. So if I for example go directly to page 3 with it, I want to keep the same behavior as if I would list the flipbook manually (odd pages are on the right).

**Comment by ts1** [comment]
Unfortunately, you can't do that directly. You'll need to modify the slider value to only include odd numbers before passing it to the flipbook. Hope that makes sense.

**Comment by Pajicc** [comment]
Okay understood, thank you for quick response!
